### ISSUE TITLE
Feature discussion: Explicit Order

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#114]
@tonsky recently published a post of [ideas for a DataScript 2.0](https://tonsky.me/blog/datascript-2/). One of the topics is lack of ordering in DataScript which equally affects datalevin. One of the suggestions is to create an order index.

I imagine this would look like `EAVO` - **E**ntity **A**ttribute **V**alue **O**rder such that order can be set on the relation-level (`EAV`) such that `ref` values can reappear in other relations with different order. @ccorcos suggested [fractional indexing](https://observablehq.com/@dgreensp/implementing-fractional-indexing) to set and update order.

@huahaiy while I'm not clear yet what the API might like and what the tradeoffs are I'm curious to know is this something you'd be open to having in datalevin?

**Comment by huahaiy** [comment]
I do not understand what you mean by "ordering". I will need to see examples. You mean "order-by" in SQL? What's wrong with ordering results afterwards? It's simple enough to add that in the query language of Datalevin. It's not a problem.

But putting order in index is a bad idea, and no database does that. The reason is simple, there are unbounded number of ordering and database system often do sorting as needed to speed up query, e.g. to allow merge joins. There's no point store a specific order in the index.

As to his blog posts, most of the concerns are either already being addressed in Datalevin, or plainly wrong. For example, the idea of removing query is just ridiculous. The only reason for many people to be interested in Datomic-like stores is the query language. It is at least the case for me. Without the query language, I wouldn't consider using such a thing.

Yes, it is hard to build fast query engines, but it is doable. I am making great progress here. 

In any case, I have very different goals from tonsky. He's a UI guy and he built Datascript to experiment with building UI in a new way. 

I want to build a database in the traditional sense. I want the database to be flexible and easy to use, so that people don't have to be a relational algebra experts to use a database, i.e. to fully realize the dream of database researchers, to have completely fool proof database systems. My ultimate ambition, is to realize the dream of early AI researchers, to have a powerful knowledge graph and reasoning platform.

**Comment by zeitstein** [comment]
Hope you don't mind a "UI guy" jumping in here.

I've been using `:xform` to solve ordering with `pull`. It would be nicer if one could work with vectors directly, but... Asami has support for [arrays](https://github.com/quoll/asami/wiki/5.-Entity-Structure#arrays). My feeling is that this produces a lot of extra datoms and can be challenging to work with. A combination of tx functions and `order-by` should be good enough. 

> this means order values need to be tracked for each possible parent

I've been solving this by wrapping the 'todo' in another entity for each parent. Makes sense for my use cases, since order is not the only attribute that is location-dependent.

Wholeheartedly agree with @huahaiy about Tonsky's query comments. However, I will say that `pull` is very useful for UI and I think it is fairly true that for many UIs you might not need queries at all. I think `pull` makes a lot of sense for the "give me my data as a denormalized tree" use cases; it is simpler than using queries.

One thing I'd like is [ref support in heterogenous tuples](https://github.com/tonsky/datascript/issues/364#issuecomment-1042109300). Any thoughts on that?

Finally, @huahaiy, following your work with great interest and excitement. Thanks!

**Comment by huahaiy** [comment]
We will need to support tuple first, then we can think about handle ref in them. Thanks for the suggestion.
