### ISSUE TITLE
Fulltext search for the empty string returns an error instead of all datoms

### ISSUE THREAD

**Issue by bzg** [juji-io/datalevin#158]
In any datalog db:

```clojure
(d/q '[:find ?e ?a ?v
       :in $ ?q
       :where [(fulltext $ ?q) [[?e ?a ?v]]]]
     db
     "")
```

returns

```
1. Unhandled java.lang.StringIndexOutOfBoundsException
   String index out of range: -1

         StringLatin1.java:   47  java.lang.StringLatin1/charAt
               String.java:  693  java.lang.String/charAt
                search.clj:   55  datalevin.search/en-analyzer
                search.clj:   29  datalevin.search/en-analyzer
                search.clj:  367  datalevin.search.SearchEngine/search
                query.cljc:  216  datalevin.query$fulltext/invokeStatic
```

I would expect searching for the empty string to return all datoms, the same way that `(filter #(re-find #"" %) ["some" "string"])` returns all the strings.

What do you think?

**Comment by huahaiy** [comment]
I wouldn't expect that. 

A full text search query should not be considered as the same as a regular expression match pattern. They are semantically very different concepts. 

Since not all datoms are full text indexed, it does not make sense to return all datoms for an empty full text search query. It is also hard to return only those datoms that are full text indexed, as we are not tracking that information. The practical value of doing this is also questionable. 

Any search engine will just ignore an empty search query, instead of dumping the search index. So it is more semantically correct for the `fulltext` function to return `false` when facing an empty search query, so the query returns nothing. 

Thanks for raising this issue. We will resolve it by return empty result for empty search query string.

**Comment by bzg** [comment]
Thanks for taking care of this issue and for explaining your choice, it makes completely sense.
