### ISSUE TITLE
Add a `re-index` function

### ISSUE THREAD

**Issue by huahaiy** [juji-io/datalevin#179]
This function will stop the world, then dump the data to a temporary directory, clear the DB, and finally reload the data. 

In addition to being a REPL convenience, it also achieves a few thing: compact the index by the virtue of loading the datoms in order in a single transaction, optimize the compression dictionary of the index (when we land compression), and re-index the full text datoms (e.g. to change the text analyzer).

**Comment by den1k** [comment]
@huahaiy it looks like all of this can be achieved by composing a few functions from `datalevin.main`. However, since that's for the `dtlv` CLI it looks like some of the deps are not on the classpath when loading from the lib. 

```clojure
(require '[datalevin.main])
Execution error (FileNotFoundException) at datalevin.server/eval96184$loading (server.clj:1).
Could not locate taoensso/timbre__init.class, taoensso/timbre.clj or taoensso/timbre.cljc on classpath.
```

Assuming this is on purpose and those deps should not be part of the lib I'm thinking either some of the dump/load code would have to move to a util or storage-util namespace so that it can be shared between `datalevin.main` and `datalevin.core`?

**Comment by huahaiy** [comment]
Wouldn't it be more useful if things in `main` are also accessible for `core`?

**Comment by den1k** [comment]
Sure though it seems there are extra dependencies in main that are not needed for the library.
