### ISSUE TITLE
Inaccurate description of Datahike in the README?

### ISSUE THREAD

**Issue by simongray** [juji-io/datalevin#18]
See: https://www.reddit.com/r/Clojure/comments/iigs1l/clojurists_together_is_funding/g37zqkc/

The guys behind Datahike appreciate being included in your list of [Alternatives](https://github.com/juji-io/datalevin#shopping-alternatives), but don't agree with the wording. Perhaps worth updating?

**Comment by huahaiy** [comment]
I have given my reason for the wording in my answer on reddit (cited here), for I think it is fairly accurate for the moment:

>I am the author of the said "annoying" README. The "experimental" qualifier obviously refers to the name sake hickhiker tree backend of Datahike. Since hickhiker tree is not a well known technology for database backend, and the Datahike's README itself said that "the on-disk schema is not fixed yet", it is fair to say that the hickhiker tree backend is still experimental.

>The essence of a storage backend is precisely those "on-disk schema" that some seem to think of as something trivially replaceable.

>Frankly, this prevailing conception of a "pluggable storage backend" as a virtue for a database is misguided, as if users do not care about the runtime performance of databases, but they do.

>Finally, if Datahike has been good enough for our use cases, I would not have started Datalevin.

However, I am open for suggestion, since I honestly not sure what the Datahike guys want their database to be. Apparently I am not the only one who are not sure, as there are people asking the same questions there.
