### ISSUE TITLE
Entity many ref remove and add bug

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#192]
I'm not sure when this appeared but it is quite serious and breaks some functionality in my services as well as some [existing code](https://github.com/juji-io/datalevin/blob/9b1ee2a13df78d4eb69950ebcc462e0f32eda23f/src/datalevin/entity.cljc#L237-L239)

running version `0.8.5`

```clojure
(def conn
  (d/create-conn
    nil
    {:id       {:db/valueType :db.type/string
                :db/unique    :db.unique/identity}
     :foo/refs {:db/valueType   :db.type/ref
                :db/cardinality :db.cardinality/many}}))
=> #'dash.entity.cell/conn

(d/transact! conn
             [{:id       "foo"
               :foo/refs [{:id "bar"}]}])
=> {:datoms-transacted 3}

(d/touch (d/entity @conn [:id "foo"]))
=> {:id "foo", :foo/refs #{#:db{:id 2}}, :db/id 1} ; <----------------- as expected

(d/transact! conn
             [[:db/retract [:id "foo"] :foo/refs]
              {:id       "foo"
               :foo/refs [{:id "bar"}]}])
=> {:datoms-transacted 1}

(d/touch (d/entity @conn [:id "foo"]))
=> {:id "foo", :db/id 1} ; <---------------- where is "bar"?

;; repeat same transaction:
(d/transact! conn
             [[:db/retract [:id "foo"] :foo/refs]
              {:id       "foo"
               :foo/refs [{:id "bar"}]}])
=> {:datoms-transacted 1}
(d/touch (d/entity @conn [:id "foo"]))
=> {:id "foo", :foo/refs #{#:db{:id 2}}, :db/id 1} ; <-                        "bar" reappears

;; repeating the last transaction will cause "bar" to toggle (appear & disappear from the entity)

```

**Comment by den1k** [comment]
Also tested with datascript and it does not have this issue

**Comment by huahaiy** [comment]
Which version did you upgrade from?

**Comment by den1k** [comment]
I’ve been almost in lockstep with releases. This is a new app that makes heavy use of replace mechanics (add & retract if the same entity annd attr in a transaction) unlike previous apps so I’m not exactly sure when this bug was introduced.

**Comment by huahaiy** [comment]
The bug was present in at least in 0.7.x. 

I am still debugging it. This is what I know so far: if you split the second tx, so that the retraction and the repeat do not appear in the same transaction, it works. 

The problem is that tx-data to be persisted on disk is incorrect, it should be adding a new datom, but somehow becomes deleting it, i.e. got `tx=-3`, instead of `tx=3`. The transaction log in db.cljc is messed up somewhere. You say datascript doesn't have this problem. It is surprising, as the logic is the same.

I will continue debugging tomorrow.

**Comment by huahaiy** [comment]
Fixed. The issue is that we transact in batch, unlike datascript that transacts one datom at a time. 

So the retracted datom can still be found in our case (since the batch is not persisted yet), and the logic will try to avoid transact it again, which leaves only the retraction remains. Now we transact always (i.e. overwrite), unless it's a unique attribute.  We will streamline these transaction logic in the future (after query engine rewrite is finished), as datalevin has different semantics from datascript.

Will try to fix the other bug, and then do a release.
