### ISSUE TITLE
Compare error

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#28]
It looks like datalevin walks collections and compares items one by one. When two items at the same index have a different type, the comparator errors:

```
(def temp-conn (d/create-conn "data/datalevin/temp"))
(d/transact! temp-conn [{:foo [:a "a"]}
                        {:foo [:a 1]}])

=> Execution error (ClassCastException) at java.lang.String/compareTo (String.java:134).
class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
```

FWIW, this only happens when the collections have the same `count` length.

**Comment by huahaiy** [comment]
Thank you for pointing out this important issue. This is not just an issue with comparing collections, but an issue of comparing arbitrary data in Clojure. When the data types do not match in Clojure, comparing them often throws exceptions. For example, `(compare :a 1)` will throw an exception. 

In the case of Datalevin, since we promise to store arbitrary Clojure data as data values, we must allow them to be compared during transactions. I think the right solution is to catch the mismatched type exception and to return unequal (doesnt' matter return 1 or -1, as we are only interested in whether they are equal).

Would you be willing to update your PR to make it more general as what is described above?

**Comment by den1k** [comment]
@huahaiy pushed a fix https://github.com/den1k/datalevin/commit/4008633aafb8b75b0d38c376760c94053827528a

Besides I noticed there's is another set of datom-compare functions that also use `compare`: https://github.com/den1k/datalevin/blob/565289f585518d4d7d26645c1942febf1e77ca11/src/datalevin/datom.cljc#L181-L215

However, from my understanding they're used on the indexes themselves. Could these possibly error as well?

**Comment by huahaiy** [comment]
Yes, I think these needs to be fixed as well.

**Comment by den1k** [comment]
Done!
