### ISSUE TITLE
Datalevin for Nodejs/javascript

### ISSUE THREAD

**Issue by ansarizafar** [juji-io/datalevin#33]
Datalevin is an amazing project. I want to use datalog with Nodejs. Is it possible to compile Datalevin to Javascript with Clojurescript?

**Comment by huahaiy** [comment]
Not right now.  However, it should be possible to do. 

I will be abstracting out common LMDB protocols so different platforms can implement in their own LMDB bindings. Right now, I am trying to get Datalevin to work with GraalVM native image, hopefully i can get it to work. I am writing a new LMDB Java wrapper in order to do this, since LMDBJava is incompatible with native image.  Once this is done, I will work on the protocols. The goal is to get a native Datalevin command line shell. 

Once the protocals are in place, we can build a node.js version of Datalevin fairly easily, since the high level code in Datalevin are Clojurescript compabible. The remaining area of work is to abstract out bit encoding, as Javascript have some differences from Java in term of data types, but it should not be too much work. 

Anyway, I can use some help if people are interested in adopt Datalevin to other platforms.

**Comment by huahaiy** [comment]
Another possibility that saves the effort of maintaining too many LMDB bindings in Datalevin, is to compile the native image of Datalevin as a shared C library, so that other languages or environment can link to it, be it node.js, python, or whatever. 

If my effort of compiling Datalevin to native is successful, I would prefer this approach.

**Comment by huahaiy** [comment]
Now native Datalevin is finished. We also defined a set of LMDB protocols that both Java and GraalVM implemented. The same can be done for node.js. This would be a good project for someone familiar with node.js to step in to implement.

**Comment by vehas** [comment]
thanks for making Datalevin,  
I want to help with node.js binding, but I also have a different scenario in mind, such as use another database binding for react-native. 

from my understanding of protocol in [imdb.cljc](https://github.com/juji-io/datalevin/blob/master/src/datalevin/lmdb.cljc)
 basically, any key-value database with a range-scan feature when having the right binding should work with Datalevin.

since this can be any key-value database implementation
I purpose to add optionals parameters (can be  {:open-kv :new-db-driver-other-than-graal-and-java})
in **open** function [not only :graal and :java in lmdb/open-kv](https://github.com/juji-io/datalevin/blob/master/src/datalevin/storage.cljc#L422)
and relate function that need to pass this param up to surface API (d/get-conn)

the benefit is getting some room for me and other people to try to implement  "lmdb binding" (which seems more like a key-value database driver) for node.js  and other clients since a basic driver can be easily made and hard to tune up to production-grade.

**Comment by huahaiy** [comment]
The protocols in the lmdb namespace are specifically tailored for LMDB. For example, DBI, renewable read only transaction, and so on, are LMDB specific features that do not exist in other key value stores. Of course, one may be able to shoehorn another key value store in there, but I am not sure it is worth the effort, for it would be simpler to get LMDB to work on that  platform. As far as I can tell, LMDB runs on everything.  Its source code is a single C file, after all. 

To be honest, if someone insists on using another key value store, my suggestion is to look elsewhere, e.g. Datahike. They seem to offer pluggable storage. I personally find pluggable storage a silly idea for a database system, where performance is of the highest importance. Each storage has its own idiosyncrasy, a pluggable storage system will have to tailor to the lowest common denominator, that means the performance is going to be mediocre at best. If I can live with that, I wouldn't start Datalevin to begin with. There are already plenty of options for that.  

`open-kv` is a multi-method, so if someone implemented another binding, see, node.js, we will just add a `:node` target in there. I don't see a need to change the function signature.

**Comment by vehas** [comment]
thanks for your explanation. I respect your design decision.
Keep up the great work.

**Comment by kriszyp** [comment]
If it helps at all, I work on/maintain the NodeJS/LMDB binding package (https://github.com/DoctorEvidence/lmdb-js). It has really good performance characteristics, and would be glad to help with making it work for a NodeJS version Datalevin, if that is of interest.

**Comment by huahaiy** [comment]
That sounds promising. I certainly welcome such an addition.

**Comment by huahaiy** [comment]
Since no one steps up, we will go C library route. Provide datalevin as a native C shared library that speaks JSON.
