### ISSUE TITLE
Question about Server/Client transactions + improving the docs

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#63]
Hi @huahaiy!

I'm in awe of your work on [server](https://github.com/juji-io/datalevin/blob/master/doc/server.md). Very excited to spin up an instance running it.

I've been reading both code and docs and was wondering about a possible edge case:

With the schema: 
```clojure 
(def schema
  {:user/email {:db/unique    :db.unique/identity
                :db/valueType :db.type/string}})
```
and an `entity`
```clojure
(def entity {:user/email "foo@example.com"})
```

The remote db had `entity` transacted into it. Since the db has never seen this `:user/email` it creates a `:db/id` for the entity, say `42`.

Now a client db connects. It would not have `entity` with `:db/id 42` available locally since it was not queried for, correct? So "Because not all the data are duplicated on all the peers" what happens when `entity` is transacted to the local client that does not know that this entity already exists on the server? Would it receive a different `:db/id`?

Could this break `:db.unique/identity` between client and server or does this get resolved somehow?

Happy to add more detail to the docs once I understand this better.

**Comment by huahaiy** [comment]
Good question. Please be assured that all the clients access to the most update-to-date data at all time, if a minor condition is met: the client and server has clock synchronization. This is a condition easily met in any reasonable server environment, where ntp or chrony installation is standard.

The trick can be seen here https://github.com/juji-io/datalevin/blob/7767eda20e06c664de2d713112b4fbf21cbabe3c/src/datalevin/db.cljc#L252

Since we are checking `db?` pre-condition whenever we access to a db, this function check the update-to-date-ness of `db` by comparing `last-modified` time between its cache and the server, and invalidate its cache if it is stale.

**Comment by den1k** [comment]
Thank you. What if the client is offline in a local database?

**Comment by huahaiy** [comment]
If the client is offline, the write is not available. 

I think I mentioned in other issues, I prefer CP over AP in the CAP trade-off. For programmers, a server unavailable is a lot easier to deal with than stale data. 

Of course, supporting offline write then syncing with server when online is a feature that can be developed if needed, but I think that's a very complicated issue. To be honest, I am not sure about the ROI.

**Comment by huahaiy** [comment]
Update doc. Should we close?
